from django.conf import settings

def global_settings(request):
    return {
        'PAYPAL_CLIENT_ID': settings.PAYPAL_CLIENT_ID,
        'GOOGLE_CALENDAR_SRC': settings.GOOGLE_CALENDAR_SRC,
        'HOLD_UNTIL': settings.HOLD_UNTIL,
        'HOLD_INDEFINITELY': settings.HOLD_INDEFINITELY,
        'SEND_HOLD': settings.SEND_HOLD,
        'SEND_CONTRACT': settings.SEND_CONTRACT,
        'RECEIVE_CONTRACT': settings.RECEIVE_CONTRACT,
        'RECEIPT_CONTRACT': settings.RECEIPT_CONTRACT,
        'SEND_DEPOSIT': settings.SEND_DEPOSIT,
        'RECEIVE_DEPOSIT': settings.RECEIVE_DEPOSIT,
        'RECEIPT_DEPOSIT': settings.RECEIPT_DEPOSIT,
        'SEND_FINAL_PAYMENT': settings.SEND_FINAL_PAYMENT,
        'RECEIVE_FINAL_PAYMENT': settings.RECEIVE_FINAL_PAYMENT,
        'RECEIPT_FINAL_PAYMENT': settings.RECEIPT_FINAL_PAYMENT,
        'INVITE_MUSICIANS': settings.INVITE_MUSICIANS,
        'ALL_MUSICIANS_BOOKED': settings.ALL_MUSICIANS_BOOKED,
        'SEND_FINAL_CONFIRMATION': settings.SEND_FINAL_CONFIRMATION,
        'RECEIVE_FINAL_CONFIRMATION': settings.RECEIVE_FINAL_CONFIRMATION,
        'SEND_MUSIC_LIST': settings.SEND_MUSIC_LIST,
        'RECEIVE_MUSIC_LIST': settings.RECEIVE_MUSIC_LIST,
        'SEND_FACT_SHEETS': settings.SEND_FACT_SHEETS,
        'ALL_FACT_SHEETS_CONFIRMED': settings.ALL_FACT_SHEETS_CONFIRMED,
        'CHECK_MUSIC_LIST': settings.CHECK_MUSIC_LIST,
        'RECEIVE_EXTRA_PAYMENT': settings.RECEIVE_EXTRA_PAYMENT,
        'SEND_EXTRA_PAYMENT': settings.SEND_EXTRA_PAYMENT,
        'RECEIPT_EXTRA_PAYMENT': settings.RECEIPT_EXTRA_PAYMENT
    }
    
